# Generated by Django 3.1.7 on 2021-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary_base', '0003_remove_meal_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='meals',
            field=models.ManyToManyField(blank=True, default='', to='food_diary_base.Meal'),
        ),
    ]
