# Generated by Django 3.1.7 on 2021-03-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary_base', '0005_auto_20210308_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(default=0, null=True),
        ),
    ]
