# Generated by Django 3.1.7 on 2021-03-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary_base', '0006_auto_20210308_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='day',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='products',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
